### PR TITLE
[IOS 9590] Enable library evolution

### PR DESCRIPTION
**Pull request by DarrenWilliams2240**
### Issues
Closes: https://banno-jha.atlassian.net/browse/IOS-9590

### Description
Library evolution needs to be enabled to ensure continued module stability and library evolution in our consuming frameworks/packages.

### Testing
Tests should pass locally.

### CODE REVIEW

**Comment by patrickhartling** [comment]
I saw these warnings. Is that anything that needs to be addressed?

```
warning: 'reachability.swift': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /.../Reachability.swift/Tests/Info.plist

warning: 'reachability.swift': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /.../Reachability.swift/Sources/Info.plist
```

**Comment by DarrenWilliams2240** [comment]
@patrickhartling I'm not seeing those warnings on my end. I wonder if this is due to a difference in Xcode versions. I'm running `Version 14.2 (14C18)`

**Comment by cathcast-jh** [comment]
I am on Xcode 14.1 and I see this warning:

`/Users/catherinecastillo/Documents/Reachability.swift/Reachability.xcodeproj The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99.`

**Review by patrickhartling — APPROVED** [review]
After discussing it with Darren, it sounds to me like the warnings are not a cause for concern. For reference, here is what I did to produce those warnings using the changes on this branch:

```
swift test
```

👍

**Comment by DarrenWilliams2240** [comment]
> I am on Xcode 14.1 and I see this warning:
> 
> `/Users/catherinecastillo/Documents/Reachability.swift/Reachability.xcodeproj The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99.`

@cathcast-jh I saw that one as well. I believe that warning is specific to the project file and, with us consuming Reachability as a package going forward, shouldn't have an affect on things. Ultimately though if that's something we want to address in this PR I could certainly get that fix into this PR.

**Comment by patrickhartling** [comment]
> > I am on Xcode 14.1 and I see this warning:
> > `/Users/catherinecastillo/Documents/Reachability.swift/Reachability.xcodeproj The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99.`
> 
> @cathcast-jh I saw that one as well. I believe that warning is specific to the project file and, with us consuming Reachability as a package going forward, shouldn't have an affect on things. Ultimately though if that's something we want to address in this PR I could certainly get that fix into this PR.

I don't think that we should alter the minimum supported OS version in the Xcode project file unless we really need to. We have a similar situation with the OneSignal SDK. It still supports iOS 9.0 and 32-bit architectures. However, with Xcode 14, Apple has removed the ability to build for 32-bit platforms. For us to be able to build the OneSignal SDK using Xcode 14 (which is not strictly required since it's Objective-C code), I had to [remove](https://github.com/Banno/OneSignal-iOS-SDK/commit/56e1766b5429f4a1d4ae118a1aa38d2495f2eb17) the custom setting for `ARCHS` in the project file and let Xcode fill in the default, thereby fixing builds with any version of Xcode.

Speaking very broadly, the less we have to modify in dependencies, the better. That's particularly true with something like an Xcode project file where merge conflicts are so common. Being able to merge our (ideally small) tweaks with changes from the upstream repository needs to be as seamless as possible. There is no way to guarantee that merging from upstream will be easy, but we can avoid introducing complexity by avoiding changes that are not truly necessary.

**Review by cathcast-jh — APPROVED** [review]

**Pull request merged**
